# Generated by Django 4.2.11 on 2024-05-08 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_category_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Donation Request",
                "verbose_name_plural": "Donation Requests",
            },
        ),
        migrations.AddField(
            model_name="donation",
            name="donation_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.donationrequest",
            ),
        ),
    ]
