# Generated by Django 4.2.11 on 2024-05-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_donationrequest_donation_donation_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationrequest",
            name="image",
            field=models.ImageField(default=0, upload_to="donation-requests/"),
            preserve_default=False,
        ),
    ]
