# Generated by Django 4.2.11 on 2024-05-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_donationrequest_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="book_image",
            field=models.ImageField(default=0, upload_to="books/"),
            preserve_default=False,
        ),
    ]
