# Generated by Django 4.2.11 on 2024-05-08 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_book_book_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="description",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="title",
        ),
    ]
